# PLUGINS
# ==========================================

# Startup
# -------
- repo: Shougo/dein.vim
- repo: rafi/awesome-vim-colorschemes
- repo: rafi/vim-badge
- repo: thinca/vim-localrc
- repo: christoomey/vim-tmux-navigator
- repo: junegunn/vim-peekaboo
- repo: tpope/vim-sleuth
- repo: sgur/vim-editorconfig
- repo: itchyny/vim-gitbranch
- repo: itchyny/vim-parenmatch
- repo: itchyny/vim-cursorword
  hook_add: |
    autocmd MyAutoCmd FileType denite,qf,nerdtree let b:cursorword=0
    autocmd MyAutoCmd InsertEnter * let b:cursorword=0
    autocmd MyAutoCmd InsertLeave * let b:cursorword=1

# Vim8 only:
- { repo: roxma/nvim-yarp, if: ! has('nvim') }
- { repo: roxma/vim-hug-neovim-rpc, if: ! has('nvim'), depends: nvim-yarp }

# Lazy Loading
# ==========================================

# Languages
# ---------
- { repo: hail2u/vim-css3-syntax, on_ft: css }
- { repo: ap/vim-css-color, on_ft: [ css, scss, sass ] }
- { repo: cakebaker/scss-syntax.vim, on_ft: [ scss, sass ]}
- { repo: groenewege/vim-less, on_ft: less }
# - { repo: othree/csscomplete.vim, on_ft: css }
- { repo: mustache/vim-mustache-handlebars, on_ft: html }
- { repo: pearofducks/ansible-vim, on_ft: [ yaml.ansible, ansible_hosts ]}

# - repo: othree/html5.vim
#   on_ft: html
#   hook_add: |
#     let g:html5_event_handler_attributes_complete = 0
#     let g:html5_rdfa_attributes_complete = 0
#     let g:html5_microdata_attributes_complete = 0
#     let g:html5_aria_attributes_complete = 0

- repo: plasticboy/vim-markdown
  on_ft: markdown
  hook_add: |
    let g:vim_markdown_folding_level = 6
    let g:vim_markdown_emphasis_multiline = 0
    let g:vim_markdown_conceal = 0
    let g:vim_markdown_frontmatter = 1
    let g:vim_markdown_new_list_item_indent = 2
    let g:vim_markdown_edit_url_in = 'vsplit'
    let g:vim_markdown_strikethrough = 1
    let g:vim_markdown_fenced_languages = [
      \ 'c++=cpp',
      \ 'viml=vim',
      \ 'bash=sh',
      \ 'ini=dosini',
      \ 'js=javascript',
      \ 'json=javascript',
      \ 'docker=Dockerfile',
      \ 'makefile=make',
      \ 'py=python'
      \ ]

- repo: rhysd/vim-gfm-syntax
  depends: vim-markdown
  on_ft: markdown
  hook_source: |
    let g:gfm_syntax_enable_always = 0
    let g:gfm_syntax_highlight_emoji = 0
    let g:gfm_syntax_enable_filetypes = ['markdown']

- repo: pangloss/vim-javascript
  on_ft: [javascript, jsx, javascript.jsx]
  hook_source: |
    let g:javascript_plugin_jsdoc = 1
    let g:javascript_plugin_flow = 1
    highlight! link jsFutureKeys PreProc

- { repo: othree/jspc.vim, on_ft: [ javascript, jsx, javascript.jsx ] }
- { repo: posva/vim-vue, on_ft: [ vue ]}
- { repo: heavenshell/vim-jsdoc, on_ft: [ javascript, jsx, javascript.jsx ] }
- { repo: jparise/vim-graphql, on_ft: [ javascript, jsx, javascript.jsx ] }
- { repo: moll/vim-node, on_ft: [ javascript, jsx, javascript.jsx ] }
- { repo: elzr/vim-json, on_ft: json }

- repo: MaxMEllon/vim-jsx-pretty
  on_ft: [ javascript, jsx, javascript.jsx ]
  depends: vim-javascript
  hook_source: let g:vim_jsx_pretty_colorful_config = 1

- { repo: leafgarland/typescript-vim, on_ft: typescript }
- { repo: Quramy/tsuquyomi, on_ft: typescript }
- { repo: posva/vim-vue, on_ft: vue }

# pangloss/javascript vs. othree/yajs
#- {repo: othree/yajs.vim, on_ft: [javascript, jsx, javascript.jsx]}
#- {repo: gavocanov/vim-js-indent, on_ft: [javascript, jsx, javascript.jsx]}
#- repo: mxw/vim-jsx
#  on_ft: [javascript, jsx, javascript.jsx]
#  hook_source: let g:jsx_ext_required = 0

- { repo: reasonml-editor/vim-reason-plus, on_ft: reason }

- repo: fatih/vim-go
  on_ft: go
  hook_source: |
    let g:go_highlight_array_whitespace_error = 0
    let g:go_highlight_chan_whitespace_error = 0
    let g:go_highlight_space_tab_error = 0
    let g:go_highlight_trailing_whitespace_error = 0
    let g:go_highlight_extra_types = 1
    let g:go_highlight_build_constraints = 1
    let g:go_highlight_extra_types = 1
    let g:go_highlight_fields = 1
    let g:go_highlight_format_strings = 1
    let g:go_highlight_functions = 1
    let g:go_highlight_function_calls = 1
    let g:go_highlight_function_parameters = 1
    let g:go_highlight_types = 1
    let g:go_highlight_generate_tags = 1
    let g:go_highlight_operators = 1
    let g:go_highlight_string_spellcheck = 0
    let g:go_highlight_variable_declarations = 0
    let g:go_highlight_variable_assignments = 0

- { repo: martinda/Jenkinsfile-vim-syntax, on_ft: Jenkinsfile }
- { repo: rust-lang/rust.vim, on_ft: rust }

- { repo: vim-python/python-syntax, on_ft: python }
- { repo: Vimjas/vim-python-pep8-indent, on_ft: python }
- { repo: vim-scripts/python_match.vim, on_ft: python }
- { repo: tmhedberg/SimpylFold, on_ft: python }
- { repo: raimon49/requirements.txt.vim, on_ft: requirements }

- { repo: StanAngeloff/php.vim, on_ft: php }
# - { repo: shawncplus/phpcomplete.vim, on_ft: php, on_i: 1 }

- { repo: tbastos/vim-lua, on_ft: lua }
- { repo: osyo-manga/vim-monster, on_ft: ruby }
- { repo: toyamarinyon/vim-swift, on_ft: swift }
- { repo: rust-lang/rust.vim, on_ft: rust }
- { repo: vim-jp/syntax-vim-ex, on_ft: vim }

- { repo: chrisbra/csv.vim, on_ft: csv }
- { repo: tpope/vim-git, on_ft: [ gitcommit, gitrebase, gitconfig ]}
- { repo: ekalinin/Dockerfile.vim, on_ft: [ Dockerfile, yaml.docker-compose ]}
- { repo: tmux-plugins/vim-tmux, on_ft: tmux }
- { repo: andreshazard/vim-logreview, on_ft: logreview }

- repo: hashivim/vim-terraform
  on_ft: terraform
  on_cmd: [ Terraform, TerraformFmt ]
  hook_source: let g:terraform_fmt_on_save = 1

- { repo: cespare/vim-toml, on_ft: toml }
- { repo: mboughaba/i3config.vim, on_ft: i3config }
- { repo: dag/vim-fish, on_ft: fish }
- { repo: jstrater/mpvim, on_ft: portfile }
- { repo: robbles/logstash.vim, on_ft: logstash }
- { repo: exu/pgsql.vim, on_ft: pgsql }
- { repo: othree/nginx-contrib-vim, on_ft: nginx }
- { repo: IN3D/vim-raml, on_ft: raml }

- repo: rust-lang/rust.vim
  on_ft: rust
  hook_source: |
    let g:rustfmt_autosave = 1

# - {repo: slashmili/alchemist.vim, on_ft: [ex, exs, eex, elixir]}
- {repo: elixir-editors/vim-elixir, on_ft: [ex, exs, eex, elixir]}

- {repo: Quramy/tsuquyomi, on_ft: [ts, typescript]}
- {repo: leafgarland/typescript-vim, on_ft: [ts, typescript]}
- {repo: jason0x43/vim-js-indent, on_ft: [ts, typescript]}

# ==========================================
# Commands
# --------
- repo: Shougo/defx.nvim
  on_cmd: Defx
  hook_source: source $VIMPATH/config/plugins/defx.vim

- repo: kristijanhusak/defx-git
  on_source: defx.nvim

- repo: kristijanhusak/defx-icons
  on_source: defx.nvim
  hook_source: |
    let g:defx_icons_column_length = 2
    let g:defx_icons_mark_icon = '✓'

- repo: scrooloose/nerdtree
  on_map: { n: <Plug> }
  trusted: 1
  hook_post_source: source $VIMPATH/config/plugins/nerdtree.vim

- { repo: Xuyuanp/nerdtree-git-plugin, on_source: nerdtree }
- { repo: t9md/vim-choosewin, on_map: { n: <Plug> }}
- { repo: kana/vim-niceblock, on_map: { x: <Plug> }}
- { repo: guns/xterm-color-table.vim, on_cmd: XtermColorTable }
- { repo: mbbill/undotree, on_cmd: UndotreeToggle }
- { repo: metakirby5/codi.vim, on_cmd: Codi }
- { repo: Shougo/vimproc.vim, build: make, on_func: vimproc# }
- { repo: reedes/vim-wordy, on_cmd: [ Wordy, NextWordy, PrevWordy ]}
- { repo: brooth/far.vim, on_cmd: [ Far, Farp, F ] }
- { repo: jreybert/vimagit, on_cmd: Magit }
- { repo: tweekmonster/helpful.vim, on_cmd: HelpfulVersion }
- { repo: lambdalisue/gina.vim, on_cmd: Gina }
- { repo: cocopon/colorswatch.vim, on_cmd: ColorSwatchGenerate }
- { repo: kana/vim-altr, on_map: { n: <Plug> }}
- { repo: lambdalisue/suda.vim, on_path: 'suda://' }

- repo: tyru/open-browser.vim
  on_map: { nxv: <Plug>(openbrowser }
  on_cmd: [ OpenBrowser, OpenBrowserSearch, OpenBrowserSmartSearch ]

- repo: tyru/open-browser-unicode.vim
  depends: open-browser.vim
  on_cmd: OpenBrowserUnicode

- repo: tyru/open-browser-github.vim
  depends: open-browser.vim
  on_cmd: [ OpenGithubFile, OpenGithubIssue, OpenGithubProject ]

- { repo: tyru/caw.vim, on_map: { nx: <Plug> }}

# - { repo: tpope/vim-commentary, on_map: <Plug>Commentary }

- repo: Shougo/vinarise.vim
  on_cmd: Vinarise
  hook_add: let g:vinarise_enable_auto_detect = 1

- repo: mzlogin/vim-markdown-toc
  on_cmd: [GenTocGFM, GenTocRedcarpet, GenTocGitLab, UpdateToc]
  hook_source: let g:vmt_auto_update_on_save = 0

- repo: easymotion/vim-easymotion
  on_map: {n: <Plug>}
  hook_source: |
    let g:EasyMotion_do_mapping = 0
    let g:EasyMotion_prompt = 'Jump to → '
    let g:EasyMotion_keys = 'fjdksweoavn'
    let g:EasyMotion_smartcase = 1
    let g:EasyMotion_use_smartsign_us = 1

- repo: chemzqm/vim-easygit
  on_cmd: [Gadd, Gcd, Glcd, Gcommit, Gblame, Gstatus, Gdiff, Gbrowse, Gstatus, Gpush]
  hook_source: let g:easygit_enable_command = 1

- repo: majutsushi/tagbar
  on_cmd: TagbarToggle
  hook_source: |
    let g:tagbar_width = 40
    if executable('jsctags')
      let g:tagbar_type_javascript = {'ctagsbin': 'jsctags'}
    endif

- repo: beloglazov/vim-online-thesaurus
  on_cmd: [ OnlineThesaurusCurrentWord, Thesaurus ]
  hook_source: let g:online_thesaurus_map_keys = 0

# ==========================================
# Interface
# ---------
- { repo: haya14busa/vim-asterisk, on_map: { nv: <Plug> }}
- { repo: rhysd/accelerated-jk, on_map: { n: <Plug> }, if: $SUDO_USER == '' }
- { repo: haya14busa/vim-edgemotion, on_map: { nv: <Plug> }}
- { repo: t9md/vim-quickhl, on_map: { nv: <Plug> }}
- { repo: rafi/vim-sidemenu, on_map: { nv: <Plug> }}

- repo: airblade/vim-gitgutter
  on_path: .*
  hook_source: |
    let g:gitgutter_map_keys = 0
    let g:gitgutter_sh = $SHELL

- repo: nathanaelkane/vim-indent-guides
  on_cmd: [IndentGuidesEnable, IndentGuidesDisable, IndentGuidesToggle]
  hook_post_source: |
    call indent_guides#init_script_vars()
    call indent_guides#highlight_colors()
  hook_add: |
    let g:indent_guides_color_change_percent = 3
    let g:indent_guides_autocmds_enabled = 0
    let g:indent_guides_default_mapping = 0
    let g:indent_guides_guide_size = 1
    let g:indent_guides_indent_levels = 15
    let g:indent_exclude = [ 'help', 'denite', 'codi' ]
    autocmd MyAutoCmd BufEnter *
      \ if ! empty(&l:filetype) && index(g:indent_exclude, &l:filetype) == -1
      \|   if g:indent_guides_autocmds_enabled == 0 && &l:expandtab
      \|     IndentGuidesEnable
      \|   elseif g:indent_guides_autocmds_enabled == 1 && ! &l:expandtab
      \|     IndentGuidesDisable
      \|   endif
      \| endif

- repo: MattesGroeger/vim-bookmarks
  on_path: .*
  hook_source: |
    let g:bookmark_auto_save_file = $VARPATH.'/bookmarks'
    let g:bookmark_no_default_key_mappings = 1
    let g:bookmark_disable_ctrlp = 1

- { repo: hotwatermorning/auto-git-diff, on_ft: gitrebase }

- repo: rhysd/committia.vim
  on_path: COMMIT_EDITMSG
  hook_source: let g:committia_min_window_width = 70

- repo: benekastah/neomake
  if: has('nvim')
  on_cmd: [ Neomake, NeomakeFile, NeomakeEnable ]
  hook_source: source $VIMPATH/config/plugins/neomake.vim
  hook_add: |
    let g:lint_types = [
      \  'yaml.ansible', 'python', 'php', 'ruby', 'vim', 'go', 'sh',
      \  'javascript', 'jsx', 'javascript.jsx', 'json', 'css',
      \  'markdown', 'html', 'yaml'
      \]
    autocmd MyAutoCmd BufWritePost *
      \  if expand('%:p') !~ $VIMPATH
      \      && index(g:lint_types, &filetype) > -1
      \      && empty(&buftype)
      \|   Neomake
      \| endif

- repo: lambdalisue/vim-improve-diff
  on_event: [ InsertLeave, BufWinLeave ]
  on_cmd: DiffOrig

- repo: junegunn/goyo.vim
  depends: limelight.vim
  on_cmd: Goyo
  hook_source: source $VIMPATH/config/plugins/goyo.vim

- repo: junegunn/limelight.vim
  on_cmd: Limelight

- repo: itchyny/calendar.vim
  on_cmd: Calendar
  hook_source: |
    let g:calendar_google_calendar = 1
    let g:calendar_google_task = 1

- repo: vimwiki/vimwiki
  on_map: { n: <Plug> }
  on_cmd: [ VimwikiIndex, VimwikiUISelect ]
  hook_add: |
    let g:vimwiki_use_calendar = 1
    let g:vimwiki_hl_headers = 1
    let g:vimwiki_hl_cb_checked = 1
    let g:vimwiki_autowriteall = 0
  hook_source: |
    let g:vimwiki_list = [
    \   {'diary_header': 'Diary',
    \     'diary_link_fmt': '%Y-%m/%d',
    \     'auto_toc': 1,
    \     'path': '~/docs/wiki/',
    \     'syntax': 'markdown',
    \     'ext': '.md'},
    \   {'path': '~/docs/blog/',
    \     'syntax': 'markdown',
    \     'ext': '.md'}
    \]

# ==========================================
# Completion
# ----------

# ==========================================
# Denite
# ------
- repo: Shougo/denite.nvim
  on_cmd: Denite
  trusted: 1
  hook_source: source $VIMPATH/config/plugins/denite.vim

- { repo: Shougo/neoyank.vim, on_event: TextYankPost, on_source: denite.nvim }
- { repo: Shougo/junkfile.vim, on_source: denite.nvim }
- { repo: chemzqm/unite-location, on_source: denite.nvim }
- { repo: chemzqm/denite-git, on_source: denite.nvim }
- { repo: rafi/vim-denite-z, on_source: denite.nvim }
- { repo: rafi/vim-denite-session, on_source: denite.nvim }

# - repo: nixprime/cpsm
#   build: 'sh -c "PY3=ON ./install.sh"'

# - repo: raghur/fruzzy
#   on_source: denite.nvim
#   hook_source: let g:fruzzy#sortonempty = 0
#   hook_post_update: call fruzzy#install()

# - { repo: rafi/vim-denite-task, on_source: denite.nvim }
# - repo: rafi/vim-denite-mpc
#   if: executable('mpc')
#   on_source: denite.nvim
#   hook_source: call denite#custom#var('mpc', 'default_view', 'date')

# ==========================================
# Operators
# ---------
- {repo: kana/vim-operator-user, lazy: 1}

- repo: kana/vim-operator-replace
  depends: vim-operator-user
  on_map: {vnx: <Plug>}

- repo: rhysd/vim-operator-surround
  depends: [vim-operator-user, vim-textobj-multiblock]
  on_map: {vnx: <Plug>}

- repo: haya14busa/vim-operator-flashy
  depends: vim-operator-user
  on_map: {nx: <Plug>}

# ==========================================
# Text objects
# ------------
- { repo: kana/vim-textobj-user, on_func: textobj#user# }
- { repo: terryma/vim-expand-region, on_map: { x: <Plug> }}
- { repo: AndrewRadev/sideways.vim, on_map: { ox: <Plug>Sideways }}
- { repo: AndrewRadev/splitjoin.vim, on_map: { n: <Plug>Splitjoin }}
- { repo: AndrewRadev/linediff.vim, on_cmd: Linediff }

- repo: AndrewRadev/dsf.vim
  on_map: {n: <Plug>Dsf}
  hook_add: let g:dsf_no_mappings = 1

- repo: osyo-manga/vim-textobj-multiblock
  depends: vim-textobj-user
  on_map: {ox: <Plug>}
  hook_add: let g:textobj_multiblock_no_default_key_mappings = 1

- repo: kana/vim-textobj-function
  depends: vim-textobj-user
  on_map: {ox: <Plug>}
  hook_add: let g:textobj_function_no_default_key_mappings = 1

#  vim: set ts=2 sw=2 tw=80 et :
